//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystem.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_消費税率
    {
        public int ID { get; set; }
        public double 税率 { get; set; }
        public System.DateTime 適用開始日 { get; set; }
    }
}
