//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 会計システム.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_仕訳
    {
        public string 伝票番号 { get; set; }
        public int 仕訳番号 { get; set; }
        public int 勘定科目コード { get; set; }
        public decimal 金額 { get; set; }
        public string 摘要 { get; set; }
        public int 貸借 { get; set; }
    }
}
