//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystem.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_会計伝票
    {
        public string 伝票番号 { get; set; }
        public System.DateTime 計上日 { get; set; }
    }
}
